apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: "01"
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: "02"
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: "03"
      protocol: UDP
      port: 6832
      targetPort: 6832
    - name: "04"
      protocol: TCP
      port: 9411
      targetPort: 9411
    - name: "05"
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: "06"
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: "07"
      protocol: TCP
      port: 14268
      targetPort: 14268
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: jaeger
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      serviceAccountName: jaeger
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.13
          ports:
            - containerPort: 9411
          env:
            - name: 'COLLECTOR_ZIPKIN_HTTP_PORT'
              value: '9411'