kind: Namespace
apiVersion: v1
metadata:
  name: api-ns
  labels:
    name: api
---
kind: Namespace
apiVersion: v1
metadata:
  name: payments-ns
  labels:
    name: payments
---
kind: Namespace
apiVersion: v1
metadata:
  name: currency-ns
  labels:
    name: cache
---