---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 9090
      protocol: http
      services:
        - name: ingress-gw
          hosts: ["*"]
