apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
    service: fake-service
  name: web-ingress
  namespace: default
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer