apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api
  namespace: api-ns
spec:
  routes:
    - match:
        http:
          header:
            - name : baggage
              regex: .*version=2.*
      destination:
        service: api
        serviceSubset: v2
        requestTimeout: 10s
        numRetries: 3
        retryOnConnectFailure: true
      # Retry Logic Added
    #- match:
    #    http:
    #      pathPrefix: /
    #  destination:
    #    service: api
    #    requestTimeout: 10s
    #    numRetries: 3
    #    retryOnConnectFailure: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: api
  namespace: api-ns
spec:
  splits:
    - weight: 50
      serviceSubset: v1
    - weight: 50
      serviceSubset: v2
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: api
  namespace: api-ns
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
    v2:
      filter: 'Service.Meta.version == v2'


