apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: api
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-v2
  labels:
    app: api
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        consul.hashicorp.com/envoy-extra-args: '--log-level debug'
        consul.hashicorp.com/service-tags: 'api, v2'
        consul.hashicorp.com/service-meta-version: v2
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.21.0
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9091'
            - name: 'UPSTREAM_URIS'
              value: 'http://payments:9090'
            - name: 'NAME'
              value: 'api-v2'
            - name: 'MESSAGE'
              value: 'API response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '10ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '15ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '20ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'
            - name: 'TRACING_ZIPKIN'
              value: 'http://simplest-collector:9411'