apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api
spec:
  routes:
    - match:
        http:
          header:
            - name : baggage
              regex: .*
      destination:
        service: api
        serviceSubset: v2
        requestTimeout: 10s
        numRetries: 3
        retryOnConnectFailure: true
      # Retry Logic Added
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api
spec:
  routes:
    - match:
        http:
          pathPrefix: /
      destination:
        service: api
        requestTimeout: 10s
        numRetries: 3
        retryOnConnectFailure: true
      # Retry Logic Added
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: api
spec:
  splits:
    - weight: 100
      serviceSubset: v1
    - weight: 0
      serviceSubset: v2
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: api
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
    v2:
      filter: 'Service.Meta.version == v2'


